const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { randomUUID } = require('node:crypto');
const { testPool } = require('./helpers/pg-pool');
const { start } = require('../server');
const { loadConfig } = require('../src/server/config');
const { createPricing } = require('../src/billing/pricing');
const modelId = 'kie:grok-imagine-video-1-5-preview';
const input = { prompt: 'Тест', duration: 8, aspect_ratio: '16:9', resolution: '720p' };
test('connection retries support both pg pool interfaces without replaying queries', async () => {
  const { retryConnections } = require('../src/database/database');
  let attempts = 0, releases = 0;
  const client = { release: () => releases++ };
  const pool = retryConnections({ connect: async () => { if (++attempts < 3) throw Object.assign(new Error('DNS'), { code: 'EAI_AGAIN' }); return client; } });
  assert.equal(await pool.connect(), client); assert.equal(attempts, 3);
  await new Promise((resolve, reject) => pool.connect((error, value, release) => { if (error) return reject(error); assert.equal(value, client); release(); resolve(); }));
  assert.equal(releases, 1);
  let denied = 0;
  const bad = retryConnections({ connect: async () => { denied++; throw Object.assign(new Error('Login denied'), { code: '28P01' }); } });
  await assert.rejects(bad.connect()); assert.equal(denied, 1);
});

test('native prices use exact minor units, explicit tariffs, no provider cost conversion', () => {
  const pricing = createPricing({ version: 'v1', models: { demo: { baseUnits: 1001, perSecondUnits: 123 } } });
  assert.equal(pricing.quote('demo', { duration: 3 }).amountUnits, 1370);
  assert.throws(() => pricing.quote('absent'), /не опубликована/);
  assert.throws(() => pricing.quote('demo', { duration: -1 }));
  assert.throws(() => createPricing({ models: { bad: { baseUnits: 1.1 } } }));
  assert.throws(() => createPricing({ models: { bad: { baseUnits: Number.MAX_SAFE_INTEGER, perSecondUnits: 1 } } }).quote('bad', { duration: 1 }));
  assert.throws(() => loadConfig({ MEDIA_AUTH_ENABLED: 'false', MEDIA_HOST: '0.0.0.0' }));
  assert.throws(() => loadConfig({ MEDIA_PUBLIC_ORIGIN: 'http://public.example' }));
});

test('OAuth, account isolation, RBAC, atomic reservations, settlement, replay and logout', { timeout: 60000 }, async t => {
  const artifacts = path.resolve(__dirname, '../artifacts'); await fs.mkdir(artifacts, { recursive: true });
  const directory = await fs.mkdtemp(path.join(artifacts, 'accounts-test-'));
  const pool = testPool(); let runtime;
  t.after(async () => { if (runtime) await runtime.close(); else await pool.end(); await fs.rm(directory, { recursive: true, force: true }); });
  let sent = 0;
  const provider = { id: 'kie', isConfigured: () => true, upload: async () => 'https://example.test/source',
    create: async () => ({ taskId: `provider-${++sent}` }), poll: async () => ({ state: 'success', creditsConsumed: 999, resultJson: '{"resultUrls":["https://example.test/result.png"]}' }), balance: async () => 8000 };
  const config = { ...loadConfig({ MEDIA_PORT: '0', MEDIA_ADMIN_IDENTITIES: 'google:owner' }), dataDirectory: directory,
    pricing: { version: 'test-v1', models: { [modelId]: { baseUnits: 2500 } } } };
  const adapter = { label: 'Test', authorize: ({ state, challenge }) => `https://identity.example/auth?state=${state}&code_challenge=${challenge}`,
    exchange: async ({ code }) => ({ subject: code, name: `Аккаунт ${code}`, ...(code === 'invited-owner' ? { verifiedEmail: 'owner@example.test' } : {}) }) };
  runtime = await start({ config, provider, pool, authProviders: new Map([['google', adapter], ['vk', adapter]]) });
  const base = `http://127.0.0.1:${runtime.server.address().port}`;
  const request = (url, options = {}) => fetch(base + url, { ...options, redirect: 'manual' });
  async function login(subject, providerName = 'google') {
    const begin = await request(`/auth/${providerName}/start`);
    const state = new URL(begin.headers.get('location')).searchParams.get('state');
    const cookie = begin.headers.get('set-cookie').split(';')[0];
    const callback = `/auth/${providerName}/callback?state=${state}&code=${subject}`;
    const wrongBrowser = await request(callback); assert.equal(wrongBrowser.headers.get('location'), '/login?error=oauth');
    const result = await request(callback, { headers: { Cookie: cookie, 'Sec-Fetch-Site': 'cross-site' } });
    assert.equal(result.status, 302); assert.equal(result.headers.get('location'), '/');
    const session = result.headers.getSetCookie()[0]; assert.match(session, /HttpOnly; SameSite=Lax/);
    const replay = await request(callback, { headers: { Cookie: cookie } }); assert.equal(replay.headers.get('location'), '/login?error=oauth');
    const authCookie = session.split(';')[0];
    const account = (await request('/api/account', { headers: { Cookie: authCookie } }).then(r => r.json())).result;
    return { cookie: authCookie, ...account };
  }
  const rpc = (user, method, args = [], extra = {}) => request(`/api/rpc/${method}`, { method: 'POST', headers: { Cookie: user.cookie, 'X-Media-Client': 'web', 'X-Media-User': user.id, 'Content-Type': 'application/json', ...extra }, body: JSON.stringify(args) });
  const result = async response => { const r = await response, body = await r.json(); assert.equal(r.status, 200, JSON.stringify(body)); return body.result; };
  assert.equal((await request('/')).headers.get('location'), '/login');
  assert.equal((await request('/api/events')).status, 401);
  assert.equal((await request('/api/sources/' + 'a'.repeat(64))).status, 401);
  const alice = await login('alice'), bob = await login('bob'), owner = await login('owner'), otherIdentity = await login('alice', 'vk');
  assert.equal(alice.role, 'user'); assert.equal(owner.role, 'admin'); assert.notEqual(otherIdentity.id, alice.id);
  assert.equal((await request('/api/admin/accounts', { headers: { Cookie: alice.cookie } })).status, 403);
  assert.equal((await request('/api/admin/codex/status')).status, 401);
  assert.equal((await request('/api/admin/codex/status', { headers: { Cookie: alice.cookie } })).status, 403);
  assert.equal((await request('/api/admin/codex/start', { method: 'POST', headers: { Cookie: alice.cookie, 'X-Media-User': alice.id, 'X-Media-Client': 'web' } })).status, 403);
  assert.equal((await request('/api/admin/codex/start', { method: 'POST', headers: { Cookie: owner.cookie } })).status, 409);
  assert.equal((await request('/api/admin/codex/status', { headers: { Cookie: owner.cookie } })).status, 503);
  assert.equal((await rpc(alice, 'getHistory', [], { 'X-Media-Account': bob.id })).status, 403);
  assert.equal((await rpc(alice, 'setCreditRate', [1])).status, 403);
  assert.equal((await rpc(alice, 'saveDrafts', [], { 'X-Media-User': bob.id })).status, 409);
  const draft = { version: 1, tabs: [{ prompt: 'Приватно Алисе' }] };
  await result(rpc(alice, 'saveDrafts', [draft]));
  assert.deepEqual(await result(rpc(alice, 'loadDrafts')), draft);
  assert.equal(await result(rpc(bob, 'loadDrafts')), null);
  const upload = await result(request('/api/source?name=x.png', { method: 'POST', headers: { Cookie: alice.cookie, 'X-Media-User': alice.id, 'X-Media-Client': 'web', 'Content-Type': 'image/png' }, body: 'image' }));
  const sourcePath = '/api/sources/' + upload.ref.split('/').at(-1);
  assert.equal((await request(sourcePath, { headers: { Cookie: bob.cookie } })).status, 400);
  assert.equal((await request(sourcePath, { headers: { Cookie: alice.cookie } })).status, 200);
  const catalog = await result(rpc(alice, 'getCatalog')); assert.equal(catalog.providers[0].id, 'media'); assert.equal(catalog.models[0].pricing, undefined);
  const empty = await result(rpc(alice, 'getBalance')); assert.equal(empty.balance, 0);
  const adminPayload = { modelId, input, requestId: randomUUID(), billingExemptActor: owner.id };
  const tariff = config.pricing.models[modelId];
  delete config.pricing.models[modelId];
  for (const user of [alice, owner]) {
    const denied = await rpc(user, 'createTask', [adminPayload, { billingExemptActor: owner.id }]);
    assert.equal(denied.status, 400);
    assert.match((await denied.json()).error, /не опубликована/);
  }
  config.pricing.models[modelId] = tariff;
  assert.equal((await rpc(owner, 'createTask', [adminPayload])).status, 400);
  assert.equal((await rpc(owner, 'createTask', [adminPayload], { 'X-Media-Account': 'legacy' })).status, 400);
  await runtime.accounts.wallet.grant(owner.id, owner.id, 5000, 'admin-test-balance', 'Тестовый баланс');
  const adminJob = await result(rpc(owner, 'createTask', [adminPayload]));
  assert.equal(adminJob.nativeQuote.amountUnits, 2500);
  assert.equal((await runtime.accounts.wallet.get(owner.id)).heldUnits, 2500);
  const adminService = await runtime.accounts.get(owner.id);
  adminService.queue.paused = false; await adminService.queue.tick(); adminService.queue.pause(); await adminService.queue.tick();
  assert.equal((await adminService.history.list())[0].state, 'success');
  assert.equal((await runtime.accounts.wallet.get(owner.id)).balanceUnits, 2500);
  assert.equal((await runtime.accounts.wallet.get(owner.id)).heldUnits, 0);
  assert.equal((await result(rpc(owner, 'createTask', [adminPayload]))).id, adminJob.id);
  assert.equal((await rpc(alice, 'createTask', [{ modelId, input, requestId: 'no-money' }])).status, 400);
  assert.equal((await result(rpc(alice, 'getHistory'))).length, 0);
  await runtime.accounts.wallet.grant(owner.id, alice.id, 5000, 'grant-once', 'Тестовый баланс');
  await runtime.accounts.wallet.grant(owner.id, alice.id, 5000, 'grant-once', 'Тестовый баланс');
  await assert.rejects(runtime.accounts.wallet.grant(owner.id, alice.id, 6000, 'grant-once', 'Тестовый баланс'));
  await assert.rejects(runtime.accounts.wallet.grant(bob.id, alice.id, 1000, 'grant-illegal', 'Нет прав'));
  const payload = { modelId, input, requestId: randomUUID() };
  const [first, duplicate] = await Promise.all([result(rpc(alice, 'createTask', [payload])), result(rpc(alice, 'createTask', [payload]))]);
  assert.equal(first.id, duplicate.id); assert.equal(first.nativeQuote.amountUnits, 2500);
  assert.equal((await result(rpc(alice, 'getBalance'))).heldUnits, 2500);
  assert.equal((await result(rpc(bob, 'getHistory'))).length, 0);
  const own = await runtime.accounts.get(alice.id);
  own.queue.paused = false; await own.queue.tick(); own.queue.pause(); await own.queue.tick();
  const finished = (await result(rpc(alice, 'getHistory')))[0];
  assert.equal(finished.state, 'success'); assert.equal(finished.creditsConsumed, undefined); assert.equal(finished.taskId, first.id);
  assert.equal((await result(rpc(alice, 'getBalance'))).balanceUnits, 2500);
  assert.equal((await result(rpc(alice, 'getBalance'))).heldUnits, 0);
  await own.history.update(first.id, { state: 'success' }); // Redelivery cannot charge twice.
  assert.equal((await result(rpc(alice, 'getBalance'))).balanceUnits, 2500);
  const resultDirectory = path.join(directory, 'accounts', alice.id, 'results');
  await fs.mkdir(resultDirectory, { recursive: true });
  const resultFile = path.join(resultDirectory, 'test.png'); await fs.writeFile(resultFile, 'private-result');
  await own.history.update(first.id, { localFiles: [{ path: resultFile, url: 'https://example.test/result.png', size: 14 }] });
  assert.equal((await request(`/api/results/${first.id}/0`, { headers: { Cookie: bob.cookie } })).status, 400);
  assert.equal(await request(`/api/results/${first.id}/0`, { headers: { Cookie: alice.cookie } }).then(r => r.text()), 'private-result');
  assert.equal((await request(`/api/results/${first.id}/0?account=${alice.id}`, { headers: { Cookie: owner.cookie } })).status, 200);
  const queued = await result(rpc(alice, 'createTask', [{ ...payload, requestId: randomUUID() }]));
  await result(rpc(alice, 'cancelQueued', [queued.id]));
  assert.equal((await result(rpc(alice, 'getBalance'))).heldUnits, 0);
  const unknown = await result(rpc(alice, 'createTask', [{ ...payload, requestId: randomUUID() }]));
  await own.history.update(unknown.id, { state: 'submitting' });
  await own.queue.recover();
  assert.equal((await own.history.list()).find(row => row.id === unknown.id).state, 'unknown');
  await result(rpc(alice, 'acknowledgeTask', [unknown.id]));
  assert.equal((await result(rpc(alice, 'getBalance'))).heldUnits, 2500);
  await assert.rejects(runtime.accounts.reconcile(bob.id, alice.id, unknown.id, 'fail', 'Отказ подтверждён'));
  await runtime.accounts.reconcile(owner.id, alice.id, unknown.id, 'fail', 'Отказ подтверждён');
  await runtime.accounts.reconcile(owner.id, alice.id, unknown.id, 'fail', 'Отказ подтверждён');
  await assert.rejects(runtime.accounts.reconcile(owner.id, alice.id, unknown.id, 'success', 'Другое решение'));
  assert.equal((await result(rpc(alice, 'getBalance'))).heldUnits, 0);
  const overspend = await Promise.all([rpc(alice, 'createTask', [{ ...payload, requestId: randomUUID() }]), rpc(alice, 'createTask', [{ ...payload, requestId: randomUUID() }])]);
  assert.deepEqual(overspend.map(response => response.status).sort(), [200, 400]);
  const lastReserved = (await overspend.find(response => response.status === 200).json()).result;
  assert.equal((await result(rpc(alice, 'getBalance'))).balance, 0);
  await result(rpc(alice, 'cancelQueued', [lastReserved.id]));
  assert.equal((await result(rpc(alice, 'getBalance'))).balance, 2.5);
  const page = await request('/', { headers: { Cookie: alice.cookie } }).then(r => r.text());
  assert.match(page, /native-costs.js/); assert.doesNotMatch(page, /src="\/shared\/costs-ui.js"/);
  assert.doesNotMatch(page, /value="510"|Тариф Kie|Стоимость 1000/);
  assert.equal((await request('/shared/tariff-snapshot.js', { headers: { Cookie: alice.cookie } })).status, 403);
  const logout = await request('/auth/logout', { method: 'POST', headers: { Cookie: alice.cookie, 'X-Media-Client': 'web', 'X-Media-User': alice.id } }); assert.equal(logout.status, 200);
  assert.equal((await rpc(alice, 'getHistory')).status, 401);
  const returning = await login('alice'); assert.equal(returning.id, alice.id);
  assert.deepEqual(await result(rpc(returning, 'loadDrafts')), draft);
  assert.ok((await pool.query('SELECT token_hash FROM media_sessions')).rows.every(row => /^[a-f0-9]{64}$/.test(row.token_hash)));
  await pool.query("UPDATE media_sessions SET expires_at=now()-interval '1 second' WHERE account_id=$1", [returning.id]);
  assert.equal((await rpc(returning, 'getHistory')).status, 401);
  const setRole = (user, accountId, role) => request('/api/admin/roles', { method: 'POST', headers: { Cookie: user.cookie, 'X-Media-User': user.id, 'X-Media-Client': 'web', 'Content-Type': 'application/json' }, body: JSON.stringify({ accountId, role, reason: 'Проверка ролей' }) });
  assert.equal((await setRole(bob, bob.id, 'admin')).status, 403);
  assert.equal((await setRole(owner, owner.id, 'user')).status, 409);
  await result(setRole(owner, bob.id, 'admin'));
  assert.equal((await rpc(bob, 'getHistory')).status, 401);
  const bobAdmin = await login('bob'); assert.equal(bobAdmin.role, 'admin');
  await result(setRole(bobAdmin, owner.id, 'user'));
  assert.equal((await request('/api/admin/accounts', { headers: { Cookie: owner.cookie } })).status, 401);
  const demoted = await login('owner'); assert.equal(demoted.role, 'user'); // Config cannot undo an explicit role edit.
  assert.equal((await setRole(bobAdmin, bob.id, 'user')).status, 409);
  const audit = await result(request('/api/admin/roles', { headers: { Cookie: bobAdmin.cookie } }));
  assert.equal(audit.length, 2); assert.ok(audit.every(row => row.reason === 'Проверка ролей'));
  await pool.query('INSERT INTO media_admin_invitations(email) VALUES($1)', ['owner@example.test']);
  assert.equal((await login('invited-owner', 'vk')).role, 'user');
  const invited = await login('invited-owner'); assert.equal(invited.role, 'admin');
  assert.equal(invited.identities[0].email, 'owner@example.test');
  assert.equal((await pool.query('SELECT consumed_by FROM media_admin_invitations')).rows[0].consumed_by, invited.id);
  await result(setRole(bobAdmin, invited.id, 'user'));
  assert.equal((await login('invited-owner')).role, 'user'); // Invitation is consumed exactly once.
  const renamed = await result(request('/api/account/profile', { method: 'POST', headers: { Cookie: bobAdmin.cookie, 'X-Media-User': bobAdmin.id, 'X-Media-Client': 'web' }, body: JSON.stringify({ name: 'Новое имя', id: invited.id, role: 'admin' }) }));
  assert.equal(renamed.name, 'Новое имя');
  assert.equal((await pool.query('SELECT display_name FROM media_accounts WHERE id=$1', [bob.id])).rows[0].display_name, 'Новое имя');
  assert.equal((await pool.query('SELECT role FROM media_accounts WHERE id=$1', [invited.id])).rows[0].role, 'user');
});
