const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
test('Kie login uses a persistent isolated profile and clears only its own storage',async()=>{
  const calls=[];const profile={setPermissionRequestHandler:f=>profile.permission=f,setPermissionCheckHandler:f=>profile.check=f,on:()=>{},cookies:{flushStore:async()=>calls.push('flush')},clearStorageData:async()=>calls.push('storage'),clearCache:async()=>calls.push('cache')};
  class Window{constructor(options){this.options=options;this.handlers={};this.webContents={on:(name,f)=>this.handlers[name]=f,setWindowOpenHandler:f=>this.popup=f};}on(){}async loadURL(url){this.url=url;}destroy(){this.destroyed=true;}}
  const context={module:{exports:{}},URL,require:()=>({BrowserWindow:Window,session:{fromPartition:name=>{assert.equal(name,'persist:kie-price-session');return profile;}}})};
  vm.runInNewContext(fs.readFileSync(require.resolve('../src/kie-session'),'utf8'),context);
  const {KieSession,allowedNavigation}=context.module.exports;const client=new KieSession();await client.open();
  assert.equal(client.window.options.webPreferences.sandbox,true);assert.equal(client.window.options.webPreferences.nodeIntegration,false);assert.equal(client.window.options.webPreferences.preload,undefined);
  for(const url of ['file:///secret','http://kie.ai','https://kie.ai.evil.test','javascript:alert(1)'])assert.equal(allowedNavigation(url),false);
  assert.equal(allowedNavigation('https://accounts.google.com/'),true);assert.equal(profile.check(),false);
  assert.equal(client.window.popup({url:'https://evil.test'}).action,'deny');
  client.window.isDestroyed=()=>false;
  client.window.webContents.getURL=()=> 'https://kie.ai/grok-imagine-video-1.5';
  client.window.webContents.executeJavaScript=async()=> 'signed-in';
  assert.equal((await client.status()).state,'signed-in');
  client.window.webContents.executeJavaScript=async()=> 'unknown';
  assert.equal((await client.status()).state,'unknown');
  client.window.webContents.executeJavaScript=async()=> 'signed-out';
  assert.equal((await client.status()).state,'signed-out');
  let executed='';client.window.webContents.executeJavaScript=async script=>{executed=script;return {state:'ok',value:19.2};};
  const quote=await client.quote('grok-imagine-video-1-5-preview',{prompt:'PRIVATE PROMPT',image_urls:[true],duration:8,resolution:'480p'});
  assert.equal(quote.credits,19.2);assert.equal(executed.includes('PRIVATE PROMPT'),false);assert.equal(executed.includes('https://local.invalid/present'),true);
  let prevented=false;client.window.handlers['will-redirect']({preventDefault:()=>prevented=true},'https://blocked.test/private-email?token=SECRET#password');
  assert.equal(prevented,true);
  client.window.handlers['did-fail-load']({},-105,'SECRET server message','https://accounts.google.com/private?token=SECRET',true);
  const report=JSON.stringify(client.diagnostics());assert.equal(report.includes('SECRET'),false);assert.equal(report.includes('private'),false);assert.equal(report.includes('password'),false);
  assert.equal(client.diagnostics().at(-1).code,-105);
  for(let n=0;n<110;n++)client.record('page_loaded','https://kie.ai/secret',200);
  assert.equal(client.diagnostics().length,100);
  await client.clear();assert.equal(client.window.destroyed,true);assert.deepEqual(calls,['storage','cache','flush']);
  assert.equal(client.diagnostics().length,0);
});
