// Isolated hidden Electron window; every exposed backend call is mocked.
const {app,BrowserWindow,ipcMain}=require('electron');
const path=require('node:path');
const assert=require('node:assert/strict');
if(process.argv.includes('--screenshot'))app.disableHardwareAcceleration();
const appRoot=process.argv.includes('--packaged')?path.resolve(process.env.AI_CLIENT_PACKAGED_PATH||path.join(__dirname,'../dist/win-unpacked/resources/app.asar')):path.resolve(__dirname,'..');
app.whenReady().then(async()=>{
  let win;
  try {
    ipcMain.handle('catalog:get',()=>require(path.join(appRoot,'src/catalog')));
    ipcMain.handle('kie-session:status',()=>({state:'signed-in',live:true,checkedAt:new Date().toISOString()}));
    ipcMain.handle('kie-session:quote',()=>null);
    ipcMain.handle('price-audit:get',()=>null);
    ipcMain.handle('price-audit:save',(_event,value)=>value);
    ipcMain.handle('price-audit:auto',()=>false);
    let favoriteIds=[];
    ipcMain.handle('favorites:get',()=>favoriteIds);
    ipcMain.handle('favorites:set',(_event,ids)=>{favoriteIds=[...ids];return favoriteIds;});
    let hasKey=true,balanceCalls=0,balanceFails=false;
    ipcMain.handle('key:status',()=>hasKey);
    ipcMain.handle('balance:get',()=>{balanceCalls++;if(balanceFails)throw new Error('Test offline');const balance=100-balanceCalls;return{balance,audit:{baseline:{balance:100,apiCredits:0,unknown:0,at:'2026-09-14T09:00:00.000Z'},current:{balance,apiCredits:balanceCalls,unknown:0,at:'2026-09-14T09:01:00.000Z'},reconciliation:{balanceSpent:balanceCalls,apiSpent:balanceCalls,difference:0}}};});
    const ref='https://local-assets.invalid/'+'a'.repeat(64);
    const records=[{id:'fixture',providerId:'kie',providerName:'Kie.ai',model:'grok-imagine-video-1-5-preview',modelName:'Grok Imagine Video 1.5',kind:'video',state:'success',createdAt:new Date().toISOString(),providerDurationMs:41400,generationDurationMs:125000,input:{prompt:'Saved scene',image_urls:[ref],duration:8,resolution:'720p',aspect_ratio:'16:9',nsfw_checker:true},sourceFiles:[{ref,name:'original.png',type:'image/png',size:3}]}];
    let enqueued,sourceCalls=0;
    let savedDrafts=null;
    let rubRate=0.51;
    ipcMain.handle('costs:get',()=>({rubPerCredit:rubRate}));
    ipcMain.handle('tariffs:descriptions',()=>require(path.join(appRoot,'src/kie-price-descriptions.json')));
    ipcMain.handle('costs:set',(_event,value)=>{rubRate=value;return{rubPerCredit:rubRate};});
    ipcMain.handle('tariffs:get',()=>({fetchedAt:new Date().toISOString(),rows:[{modelDescription:'grok-imagine-video-1-5-preview, image-to-video, 480p',creditPrice:'2.4',creditUnit:'per second'},{modelDescription:'grok-imagine-video-1-5-preview, image-to-video, 720p',creditPrice:'4.5',creditUnit:'per second'}]}));
    let templateRows=[];
    ipcMain.handle('templates:list',()=>templateRows);
    ipcMain.handle('templates:save',(_event,value)=>{const row={...value,id:value.id||'template-1'};templateRows=[row];return row;});
    ipcMain.handle('templates:remove',(_event,id)=>{templateRows=templateRows.filter(row=>row.id!==id);});
    ipcMain.handle('drafts:load',()=>savedDrafts);
    ipcMain.handle('drafts:save',(_event,data)=>{savedDrafts=structuredClone(data);return true;});
    ipcMain.handle('history:list',()=>records);
    ipcMain.handle('source:save',(_event,file)=>{sourceCalls++;return {ref:'https://local-assets.invalid/'+'b'.repeat(64),name:file.name,type:file.type,size:file.bytes.length};});
    ipcMain.handle('source:preview',()=> 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=');
    ipcMain.handle('task:create',(_event,request)=>{enqueued=request;return{id:'new',state:'queued'};});
    ipcMain.handle('storage:get',()=>({directory:'',autoSave:false}));
    let concurrency=3,queueStarts=0;
    ipcMain.handle('queue:status',()=>({paused:true,error:null,concurrency}));
    ipcMain.handle('queue:concurrency',(_event,value)=>{concurrency=value;return value;});
    ipcMain.handle('queue:start',()=>{queueStarts++;return true;});
    win=new BrowserWindow({show:false,width:1240,height:900,webPreferences:{preload:path.join(appRoot,'src/preload.js'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});
    await win.loadFile(path.join(appRoot,'src/index.html'));
    const count=await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{const count=document.querySelector('#model').options.length;if(count){clearInterval(t);resolve(count)}else if(++n>100){clearInterval(t);reject(new Error('UI did not initialize'))}},50)})`);
    assert.ok(count>=143);
    const providerPlacement=await win.webContents.executeJavaScript(`({inHeader:Boolean($('provider').closest('header')),inAside:Boolean($('provider').closest('aside')),firstSidebarLabel:document.querySelector('aside > label')?.textContent})`);
    assert.deepEqual(providerPlacement,{inHeader:true,inAside:false,firstSidebarLabel:'Модель'});
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#modelInfo')"),null);
    await win.webContents.executeJavaScript('window.confirm=()=>true;void 0');
    assert.equal(balanceCalls,1);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#balance').textContent"),'99');
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#balanceAudit').textContent"),/расход совпадает/);
    const favorites=await win.webContents.executeJavaScript(`(async()=>{const original=$('model').value;$('toggleFavorite').click();await new Promise(resolve=>setTimeout(resolve,20));const added=$('favoriteModels').querySelectorAll('.favorite-row').length;const starred=$('toggleFavorite').textContent.includes('Убрать');document.querySelector('#favoriteModels .favorite-select').click();const selected=$('model').value===original;document.querySelector('#favoriteModels .favorite-remove').click();await new Promise(resolve=>setTimeout(resolve,20));return {added,starred,selected,empty:$('favoriteModels').textContent.includes('Добавьте часто используемые модели')};})()`);
    assert.deepEqual(favorites,{added:1,starred:true,selected:true,empty:true});assert.deepEqual(favoriteIds,[]);
    const timingText=await win.webContents.executeJavaScript("document.querySelector('#historyList').textContent");
    assert.match(timingText,/Генерация Kie: 41,4 с/);assert.match(timingText,/Общее ожидание: 2 мин 5 с/);
    const fields=await win.webContents.executeJavaScript(`(()=>{const select=document.querySelector('#model');select.value='kie:veo3_fast:FIRST_AND_LAST_FRAMES_2_VIDEO';select.dispatchEvent(new Event('change'));return [...document.querySelectorAll('[data-key]')].map(el=>({key:el.dataset.key,type:el.type,required:el.required}))})()`);
    assert.ok(fields.some(f=>f.key==='firstFrame'&&f.type==='file'&&f.required));
    assert.ok(fields.some(f=>f.key==='lastFrame'&&f.type==='file'&&!f.required));
    assert.ok(fields.findIndex(f=>f.key==='firstFrame')<fields.findIndex(f=>f.key==='lastFrame'));
    assert.equal(await win.webContents.executeJavaScript(`document.querySelector('[data-key="firstFrame"]').closest('.field').querySelector('.hint').textContent`),'Один файл');
    const dropped=await win.webContents.executeJavaScript(`(()=>{
      const input=document.querySelector('[data-key="firstFrame"]'),last=document.querySelector('[data-key="lastFrame"]');
      const transfer=new DataTransfer();transfer.items.add(new File(['image'],'drop.png',{type:'image/png'}));
      input.parentElement.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));
      const result=[input.files[0]?.name,last.files.length];
      const bad=new DataTransfer();bad.items.add(new File(['bad'],'bad.txt',{type:'text/plain'}));
      input.parentElement.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:bad}));
      result.push(input.files[0]?.name);input.value='';input.dispatchEvent(new Event('change',{bubbles:true}));return result;
    })()`);
    assert.deepEqual(dropped,['drop.png',0,'drop.png']);
    const staleError=await win.webContents.executeJavaScript(`(()=>{
      setStatus('Можно добавить не более 1 файлов в это поле.',true);switchWorkTab(1);const tab=$('status').classList.contains('hidden');switchWorkTab(0);
      setStatus('Можно добавить не более 1 файлов в это поле.',true);$('model').selectedIndex=1;$('model').dispatchEvent(new Event('change'));const model=$('status').classList.contains('hidden');return {tab,model};
    })()`);
    assert.deepEqual(staleError,{tab:true,model:true});
    const individualRemoval=await win.webContents.executeJavaScript(`(()=>{
      const select=$('model');select.value='kie:bytedance/seedance-1.5-pro';select.dispatchEvent(new Event('change'));
      const duration=$('fields').querySelector('[data-key="duration"]'),durationState={value:duration.value,note:duration.parentElement.querySelector('.hint').textContent};
      const input=$('fields').querySelector('[data-key="input_urls"]'),transfer=new DataTransfer();transfer.items.add(new File(['one'],'one.png',{type:'image/png'}));transfer.items.add(new File(['two'],'two.png',{type:'image/png'}));input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));
      const before=$('fields').querySelectorAll('.source-thumbnail-remove').length;$('fields').querySelector('.source-thumbnail-remove').click();
      return {durationState,before,after:$('fields').querySelectorAll('.source-thumbnail-remove').length,files:[...input.files].map(file=>file.name),label:$('fields').querySelector('[data-saved-key="input_urls"]').textContent};
    })()`);
    assert.deepEqual(individualRemoval,{durationState:{value:'4',note:'4 сек.'},before:2,after:1,files:['two.png'],label:'two.png'});
    const kling25=await win.webContents.executeJavaScript(`(()=>{const select=document.querySelector('#model');select.value='kie:kling/v2-5-turbo-image-to-video-pro';select.dispatchEvent(new Event('change'));const cfg=document.querySelector('[data-key="cfg_scale"]');return {files:[...document.querySelectorAll('#fields input[type="file"]')].map(f=>f.dataset.key),slider:cfg.parentElement.querySelector('.parameter-slider')?.step,min:cfg.min,max:cfg.max}})()`);
    assert.deepEqual(kling25,{files:['image_url','tail_image_url'],slider:'0.1',min:'0',max:'1'});
    const filtered=await win.webContents.executeJavaScript(`(()=>{document.querySelector('#modelSearch').value='Veo';document.querySelector('#modelSearch').dispatchEvent(new Event('input'));return document.querySelector('#model').options.length})()`);
    assert.equal(filtered,8);
    const structuredResult=await win.webContents.executeJavaScript(`(async()=>{
      const value=[{name:'hero',description:'Main character',element_input_urls:['https://example.com/front.png','https://example.com/side.png']}];
      const schema={type:'array',maxItems:3,items:{type:'object',required:['name','description','element_input_urls'],properties:{name:{type:'string'},description:{type:'string'},element_input_urls:{type:'array',minItems:2,items:{type:'string'}}}}};
      const editor=window.structuredField(schema,'elements',false,value,()=>{throw new Error('Unexpected upload')});
      document.body.append(editor.element);
      const restored=await editor.read();
      editor.set(undefined);const empty=await editor.read();
      editor.set(value);const again=await editor.read();editor.element.remove();
      const bool=window.structuredField({type:'boolean'},'audio',true,false,()=>{});document.body.append(bool.element);const falseValid=bool.element.querySelector('input').checkValidity();const falseValue=await bool.read();bool.element.remove();
      const alternative=window.structuredField({oneOf:[{type:'object',required:['task_id'],properties:{task_id:{type:'string'}}},{type:'object',required:['image_url'],properties:{image_url:{type:'string'}}}]},'Режим',true,{image_url:'https://example.com/image.png'},()=>{});document.body.append(alternative.element);const branch=await alternative.read();alternative.element.remove();
      const ordered=window.structuredField({type:'array',items:{type:'integer'}},'mask_indexs',true,[1,2],()=>{});document.body.append(ordered.element);[...ordered.element.querySelectorAll('button')].find(b=>b.textContent==='↓').click();const reordered=await ordered.read();ordered.element.remove();
      return {restored,emptyOmitted:empty===undefined,again,falseValid,falseValue,branch,reordered};
    })()`);
    assert.deepEqual(structuredResult.restored,structuredResult.again);
    assert.equal(structuredResult.restored[0].element_input_urls.length,2);
    assert.equal(structuredResult.emptyOmitted,true);
    assert.equal(structuredResult.falseValid,true);assert.equal(structuredResult.falseValue,false);
    assert.deepEqual(structuredResult.branch,{image_url:'https://example.com/image.png'});
    assert.deepEqual(structuredResult.reordered,[2,1]);
    const allForms=await win.webContents.executeJavaScript(`(()=>{document.querySelector('#modelSearch').value='';document.querySelector('#modelSearch').dispatchEvent(new Event('input'));const select=document.querySelector('#model');let rendered=0;for(const option of [...select.options]){select.value=option.value;select.dispatchEvent(new Event('change'));if(document.querySelector('#title').textContent==='Модели не найдены')throw new Error(option.value);rendered++;}return rendered})()`);
    assert.equal(allForms,count);
    const repeatLayout=await win.webContents.executeJavaScript(`(async()=>{
      const frame=()=>[document.querySelector('header'),$('appMain'),document.querySelector('#appMain > section')].map(el=>{const r=el.getBoundingClientRect();return [r.top,r.bottom,el.scrollTop];});
      document.querySelector('.input-panel').scrollTop=120;
      $('tabHistory').click();document.querySelector('.history-entry').open=true;
      document.querySelector('[data-repeat-id="fixture"]').click();
      await new Promise(resolve=>setTimeout(resolve,700));
      return {after:frame(),height:innerHeight,formScroll:document.querySelector('.input-panel').scrollTop,generation:!$('pageGeneration').hidden};
    })()`);
    assert.deepEqual(repeatLayout.after,[[0,68,0],[68,repeatLayout.height,0],[68,repeatLayout.height,0]],'Repeat must keep the workspace inside the viewport');
    assert.equal(repeatLayout.formScroll,0);assert.equal(repeatLayout.generation,true);
    console.log('PASS: History repeat keeps the header and workspace in the viewport and resets only the form pane.');
    if(process.argv.includes('--repeat-layout-only')){win.destroy();app.exit(0);return;}
    const repeat=await win.webContents.executeJavaScript(`(async()=>{
      [...document.querySelectorAll('#historyList button')].find(b=>b.textContent==='Изменить и повторить').click();
      const input=await collectInput();
      const label=document.querySelector('[data-saved-key="image_urls"]').textContent;
      const valid=document.querySelector('#generationForm').checkValidity();
      document.querySelector('#generationForm').requestSubmit();return{input,label,valid};
    })()`);
    assert.equal(repeat.input.image_urls[0],ref);assert.equal(repeat.label,'original.png');assert.equal(repeat.valid,true);
    assert.match(await win.webContents.executeJavaScript("$('estimatedCost').textContent"),/36 кредитов · 18,36 ₽/);
    assert.match(await win.webContents.executeJavaScript("$('tariffDescription').textContent"),/2\.4 credits/);
    await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(document.querySelector('#status').textContent.includes('Генерация запущена')){clearInterval(t);resolve()}else if(++n>100){clearInterval(t);reject(new Error(document.querySelector('#status').textContent))}},30)})`);
    assert.equal(queueStarts,1);
    assert.equal(enqueued.input.image_urls[0],ref);assert.equal(enqueued.sourceFiles[0].name,'original.png');assert.equal(sourceCalls,0);
    const tabs=await win.webContents.executeJavaScript(`(async()=>{
      const firstModel=$('model').value;const firstFields=$('fields');
      switchWorkTab(1);$('model').value=firstModel;renderModel();
      $('fields').querySelector('[data-key="prompt"]').value='Second scene';
      const fileInput=$('fields').querySelector('[data-key="image_urls"]');const transfer=new DataTransfer();transfer.items.add(new File(['fixture'],'second.png',{type:'image/png'}));fileInput.files=transfer.files;fileInput.dispatchEvent(new Event('change'));
      switchWorkTab(2);$('model').value=firstModel;renderModel();$('fields').querySelector('[data-key="prompt"]').value='Third scene';
      switchWorkTab(1);const second={prompt:$('fields').querySelector('[data-key="prompt"]').value,file:$('fields').querySelector('[data-key="image_urls"]').files[0].name};
      switchWorkTab(2);const third=$('fields').querySelector('[data-key="prompt"]').value;
      switchWorkTab(0);const original=await collectInput();
      return {second,third,original,sameNode:$('fields')===firstFields,count:$('workTabs').children.length,valid:$('generationForm').checkValidity()};
    })()`);
    assert.equal(tabs.count,3);assert.equal(tabs.sameNode,true);assert.equal(tabs.valid,true);assert.equal(tabs.original.prompt,'Saved scene');assert.equal(tabs.original.image_urls[0],ref);assert.deepEqual(tabs.second,{prompt:'Second scene',file:'second.png'});assert.equal(tabs.third,'Third scene');assert.equal(enqueued.workspace,1);
    const layout=await win.webContents.executeJavaScript(`(()=>{const form=document.querySelector('#generationForm').getBoundingClientRect();const panel=document.querySelector('.preview-panel').getBoundingClientRect();return {right:panel.left>=form.right,aligned:Math.abs(panel.top-form.top)<2,overflow:document.documentElement.scrollWidth>innerWidth}})()`);
    assert.equal(layout.right,true);assert.equal(layout.aligned,true);assert.equal(layout.overflow,false);
    const scrolling=await win.webContents.executeJavaScript(`(()=>{
      const left=document.querySelector('aside'),middle=document.querySelector('.input-panel'),right=document.querySelector('.preview-panel');
      const head=document.querySelector('.generation-header');const top=head.getBoundingClientRect().top;
      const filler=document.createElement('div');filler.textContent='Scroll fixture '.repeat(2000);right.append(filler);
      left.scrollTop=100;middle.scrollTop=120;right.scrollTop=80;
      const result={left:left.scrollTop>0,middle:middle.scrollTop>0,right:right.scrollTop>0,fixed:head.getBoundingClientRect().top===top,body:document.scrollingElement.scrollTop===0};
      filler.remove();left.scrollTop=0;middle.scrollTop=0;right.scrollTop=0;return result;
    })()`);
    assert.deepEqual(scrolling,{left:true,middle:true,right:true,fixed:true,body:true});
    records.unshift({id:'active',providerName:'Kie.ai',modelName:'Test video',state:'generating',progress:42,workspace:1,createdAt:new Date().toISOString(),input:{}});
    await win.webContents.executeJavaScript(`(()=>{const old=document.createElement('video');old.dataset.oldResult='true';$('results').append(old);previewSignature='';})()`);
    await win.webContents.executeJavaScript('previewSelection=null');
    await win.webContents.executeJavaScript('refreshHistory()');
    assert.equal(await win.webContents.executeJavaScript("$('results').children.length"),0);
    assert.equal(await win.webContents.executeJavaScript("$('previewEmpty').classList.contains('hidden')"),false);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#progressBar').value"),42);
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#queueTasks').textContent"),/42%/);
    const workspaceQueue=await win.webContents.executeJavaScript(`(()=>{switchWorkTab(1);const other=$('queueTasks').textContent;switchWorkTab(0);return {other,current:$('queueTasks').textContent};})()`);
    assert.match(workspaceQueue.other,/Нет активных или ожидающих задач/);assert.doesNotMatch(workspaceQueue.other,/Test video/);assert.match(workspaceQueue.current,/Test video/);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#queueTasks').getBoundingClientRect().bottom < document.querySelector('.preview-heading').getBoundingClientRect().top"),true);
    await win.webContents.executeJavaScript("document.querySelector('#queueConcurrency').value='3';document.querySelector('#queueConcurrency').dispatchEvent(new Event('change'))");
    await win.webContents.executeJavaScript('new Promise(r=>setTimeout(r,100))');assert.equal(concurrency,3);
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#generationProgress').textContent"),/42%/);
    delete records[0].progress;await win.webContents.executeJavaScript('refreshHistory()');
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#progressBar').hasAttribute('value')"),false);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#progressBar').classList.contains('hidden')"),true);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#queueTasks progress')===null"),true);
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#progressDetails').textContent"),/Процент готовности не передан/);
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#generationProgress').textContent"),/Генерация идёт · результат ещё не готов/);
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#generationProgress').classList.contains('is-active')"),true);
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#queueTasks').textContent"),/Генерация идёт/);
    records.shift();await win.webContents.executeJavaScript('refreshHistory()');
    const beforeCompletion=balanceCalls;
    records.unshift({id:'finished',providerId:'kie',providerName:'Kie.ai',modelName:'Test',state:'success',input:{}});
    await win.webContents.executeJavaScript('refreshHistory()');
    await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(r,100))`);
    assert.equal(balanceCalls,beforeCompletion+1);
    await win.webContents.executeJavaScript('refreshHistory()');
    assert.equal(balanceCalls,beforeCompletion+1);
    records[0]={...records[0],id:'failed',state:'fail'};
    await win.webContents.executeJavaScript('refreshHistory()');
    await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(r,100))`);
    assert.equal(balanceCalls,beforeCompletion+2);
    hasKey=false;
    await win.webContents.executeJavaScript('refreshProviderAccount()');
    assert.equal(balanceCalls,beforeCompletion+2);
    hasKey=true;balanceFails=true;
    const statusBefore=await win.webContents.executeJavaScript("document.querySelector('#status').textContent");
    await win.webContents.executeJavaScript('refreshBalance({automatic:true})');
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#status').textContent"),statusBefore);
    balanceFails=false;records.shift();
    console.log('PASS: Balance loads on startup, refreshes once per completed/failed task, skips missing keys and handles offline errors without replacing task status.');
    const fs=require('node:fs/promises');
    const fixtureDir=path.resolve(__dirname,'../artifacts/media-fixtures');await fs.mkdir(fixtureDir,{recursive:true});
    for(const [width,height] of [[320,180],[180,320],[240,240]]){
      const bytes=await win.webContents.executeJavaScript(`(async()=>{
        const canvas=document.createElement('canvas');canvas.width=${width};canvas.height=${height};
        const ctx=canvas.getContext('2d');ctx.fillStyle='#6357c9';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='white';ctx.font='20px sans-serif';ctx.fillText('${width} × ${height}',10,40);
        const stream=canvas.captureStream(0);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'});const chunks=[];
        const done=new Promise(resolve=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=resolve;});
        recorder.start();stream.getVideoTracks()[0].requestFrame();await new Promise(r=>setTimeout(r,150));recorder.stop();await done;stream.getTracks().forEach(t=>t.stop());
        return Array.from(new Uint8Array(await new Blob(chunks).arrayBuffer()));
      })()`);
      const filename=path.join(fixtureDir,`${width}x${height}.webm`);await fs.writeFile(filename,Buffer.from(bytes));
      const previewUrl=require('node:url').pathToFileURL(filename).href;
      const remote='https://expired.invalid/result.webm';
      const fixture={id:'media-test',kind:'video',state:'success',resultJson:{resultUrls:[remote]},localFiles:[{url:remote,previewUrl,exists:true}]};
      const dimensions=await win.webContents.executeJavaScript(`(async()=>{
        showResults(${JSON.stringify(fixture)});
        document.querySelector('#previewEmpty').classList.add('hidden');
        const video=document.querySelector('#results video');
        await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Video metadata timeout')),5000);video.onloadedmetadata=()=>{clearTimeout(timer);resolve();};video.onerror=()=>{clearTimeout(timer);reject(new Error('Local video failed'));};});
        return {width:video.videoWidth,height:video.videoHeight,fit:getComputedStyle(video).objectFit,src:video.currentSrc};
      })()`);
      assert.equal(dimensions.width,width);assert.equal(dimensions.height,height);assert.equal(dimensions.fit,'contain');assert.equal(dimensions.src,previewUrl);
      assert.equal(await win.webContents.executeJavaScript(`document.querySelector('#fields .source-thumbnails img').naturalWidth`),1);
      await win.webContents.executeJavaScript(`document.querySelector('#results button').onclick()`,true);
      await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(document.fullscreenElement){clearInterval(t);resolve();}else if(++n>50){clearInterval(t);reject(new Error('Fullscreen failed: '+$('status').textContent));}},20);})`);
      assert.equal(await win.webContents.executeJavaScript(`getComputedStyle(document.querySelector('#results video')).objectFit`),'contain');
      await win.webContents.executeJavaScript('document.exitFullscreen()');
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    console.log('PASS: Local WebM playback for landscape, portrait and square videos; contain scaling and fullscreen. No remote generation.');
    await win.webContents.executeJavaScript('saveWorkspaceDrafts()');
    assert.equal(savedDrafts.tabs.length,5);assert.equal(savedDrafts.tabs[1].values.prompt.value,'Second scene');assert.equal(savedDrafts.tabs[1].sourceFiles.at(-1).name,'second.png');
    savedDrafts.tabs=savedDrafts.tabs.slice(0,3); // Legacy three-tab save.
    await win.webContents.executeJavaScript(`(async()=>{
      const editor=window.structuredField({type:'array',items:{type:'object',properties:{prompt:{type:'string'},duration:{type:'integer'}}}},'scenes',true,[{prompt:'unfinished',duration:3}],()=>{});
      const snapshot=await editor.snapshot(()=>{});const copy=window.structuredField({type:'array',items:{type:'object',properties:{prompt:{type:'string'},duration:{type:'integer'}}}},'scenes',true,undefined,()=>{});copy.restore(snapshot);
      if(JSON.stringify(await copy.snapshot(()=>{}))!==JSON.stringify(snapshot))throw new Error('Nested draft changed');
      draftsReady=false;
    })()`);
    await win.loadFile(path.join(appRoot,'src/index.html'));
    await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const timer=setInterval(()=>{if(draftsReady){clearInterval(timer);resolve();}else if(++n>100){clearInterval(timer);reject(new Error('Draft restore timeout'));}},30);})`);
    const restoredDraft=await win.webContents.executeJavaScript(`(async()=>{const first=await collectInput();switchWorkTab(1);const second=await collectInput();switchWorkTab(2);const third=$('fields').querySelector('[data-key="prompt"]').value;switchWorkTab(0);return {first,second,third};})()`);
    assert.equal(restoredDraft.first.prompt,'Saved scene');assert.equal(restoredDraft.second.prompt,'Second scene');assert.equal(restoredDraft.second.image_urls[0],'https://local-assets.invalid/'+'b'.repeat(64));assert.equal(restoredDraft.third,'Third scene');
    console.log('PASS: Three drafts and local source references survive a fresh renderer, with nested editable state preserved and no generation submitted.');
    const beforeTemplates=structuredClone(enqueued);
    assert.equal(templateRows.length,0);
    await win.webContents.executeJavaScript(`(async()=>{window.confirm=()=>true;const target=$('fields').querySelector('[data-key="prompt"]');await openPromptLibrary(target,'save');const dialog=document.querySelector('.prompt-library');dialog.querySelector('[aria-label="Название шаблона"]').value='Вертолёт';dialog.querySelector('textarea').value='Helicopter over the sea';dialog.querySelector('form').requestSubmit();})()`);
    await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(r,100))`);
    assert.equal(templateRows[0].text,'Helicopter over the sea');
    const templateApplied=await win.webContents.executeJavaScript(`(()=>{const dialog=document.querySelector('.prompt-library');const search=dialog.querySelector('input[type="search"]');search.value='вертолет';search.dispatchEvent(new Event('input'));const found=dialog.querySelectorAll('.template-list article').length;const model=$('model').value;dialog.querySelector('.template-list button').click();return {found,sameModel:$('model').value===model,prompt:$('fields').querySelector('[data-key="prompt"]').value,refs:restoredFiles.image_urls};})()`);
    assert.equal(templateApplied.found,1);assert.equal(templateApplied.sameModel,true);assert.equal(templateApplied.prompt,'Helicopter over the sea');assert.deepEqual(templateApplied.refs,[ref]);assert.deepEqual(enqueued,beforeTemplates);
    await win.webContents.executeJavaScript(`(async()=>{await openPromptLibrary($('fields').querySelector('[data-key="prompt"]'),'browse');const dialog=document.querySelector('.prompt-library');[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Редактировать').click();dialog.querySelector('[aria-label="Название шаблона"]').value='Полёт';dialog.querySelector('form').requestSubmit();})()`);
    await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(r,100))`);assert.equal(templateRows[0].name,'Полёт');
    await win.webContents.executeJavaScript(`[...document.querySelectorAll('.prompt-library button')].find(b=>b.textContent==='Удалить').click()`);
    await win.webContents.executeJavaScript(`new Promise(r=>setTimeout(r,100))`);assert.equal(templateRows.length,0);
    await win.webContents.executeJavaScript(`document.querySelector('.prompt-library').close()`);
    console.log('PASS: Manual template save/search/apply/edit/delete; model and images unchanged; no automatic library writes or generation.');
    const navigation=await win.webContents.executeJavaScript(`(async()=>{
      const original=historyRecords;const draft=await collectInput();
      const fixture=original.find(row=>row.id==='fixture');
      historyRecords=Array.from({length:25},(_,index)=>({...fixture,id:'page-'+index,input:{...fixture.input,prompt:'History item '+index}}));renderHistory();
      $('tabHistory').click();
      const historyOnly=$('pageGeneration').hidden&&$('pageSpending').hidden&&!$('pageHistory').hidden&&document.querySelector('#appMain > aside').hidden;
      const firstCount=$('historyList').children.length;
      $('historyNext').click();$('historyNext').click();
      const lastCount=$('historyList').children.length;const lastDisabled=$('historyNext').disabled;
      $('historySearch').value='History item 24';$('historySearch').dispatchEvent(new Event('input'));
      const found=$('historyList').children.length===1&&$('historyList').textContent.includes('History item 24');
      $('tabSpending').click();const spendingOnly=$('pageHistory').hidden&&!$('pageSpending').hidden&&$('spendSummary').closest('[role="tabpanel"]').id==='pageSpending';
      $('tabGeneration').click();const kept=JSON.stringify(await collectInput())===JSON.stringify(draft);
      previewSelection='page-24';updatePreview();$('historySearch').value='';historyPage=0;renderHistory();$('editPreview').click();
      const repeated=(await collectInput()).prompt==='History item 24'&&!$('pageGeneration').hidden;
      $('tabHistory').click();[...$('historyList').querySelectorAll('button')].find(button=>button.textContent==='Просмотр').click();
      const opened=$('historyPreview').open&&!$('pageHistory').hidden&&$('pageGeneration').hidden;
      $('closeHistoryPreview').click();
      historyRecords=original;historyPage=0;previewSelection=null;renderHistory();updatePreview();
      return {historyOnly,firstCount,lastCount,lastDisabled,found,spendingOnly,kept,repeated,opened};
    })()`);
    assert.deepEqual(navigation,{historyOnly:true,firstCount:10,lastCount:5,lastDisabled:true,found:true,spendingOnly:true,kept:true,repeated:true,opened:true});
    console.log('PASS: Separate generation/history/spending tabs; 25 records paginated and searched; drafts preserved; off-page repeat and result navigation work.');
    await win.webContents.executeJavaScript(`(async()=>{
      for(const count of [1,2,3,4,5]){await window.desktop.setConcurrency(count);await refreshHistory();if($('workTabs').children.length!==count)throw new Error('Wrong tab count: '+count);}
      switchWorkTab(4);window.confirm=()=>true;renderHistory();document.querySelector('[data-repeat-id="fixture"]').click();
      $('fields').querySelector('[data-key="prompt"]').value='Fifth preserved scene';
      await window.desktop.setConcurrency(2);await refreshHistory();
      if(currentTab>=2)throw new Error('Hidden workspace remained active');
      await saveWorkspaceDrafts();draftsReady=false;
    })()`);
    assert.equal(savedDrafts.tabs[4].values.prompt.value,'Fifth preserved scene');
    assert.equal(savedDrafts.tabs[4].sourceFiles[0].name,'original.png');
    await win.loadFile(path.join(appRoot,'src/index.html'));
    await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(draftsReady){clearInterval(t);resolve();}else if(++n>100){clearInterval(t);reject(new Error('Five drafts failed to restore'));}},30);})`);
    const restoredFive=await win.webContents.executeJavaScript(`(async()=>{
      const visible=$('workTabs').children.length;
      await window.desktop.setConcurrency(5);await refreshHistory();switchWorkTab(4);
      const input=await collectInput();const result={visible,count:$('workTabs').children.length,prompt:input.prompt,ref:input.image_urls[0]};
      await window.desktop.setConcurrency(1);await refreshHistory();result.active=currentTab;await window.desktop.setConcurrency(5);await refreshHistory();switchWorkTab(4);
      $('generationForm').requestSubmit();return result;
    })()`);
    assert.deepEqual(restoredFive,{visible:2,count:5,prompt:'Fifth preserved scene',ref,active:0});
    await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if($('status').textContent==='Генерация запущена.'){clearInterval(t);resolve();}else if(++n>100){clearInterval(t);reject(new Error($('status').textContent));}},30);})`);
    assert.equal(enqueued.workspace,5);
    console.log('PASS: 1–5 tabs follow concurrency; hidden fifth draft and sources survive restart at 2; legacy saves restore; fifth task carries workspace 5.');
    await win.webContents.executeJavaScript(`(async()=>{
      switchWorkTab(0);$('modelSearch').value='пкщл';$('modelSearch').dispatchEvent(new Event('input'));
      await saveWorkspaceDrafts();draftsReady=false;
    })()`);
    assert.equal(savedDrafts.tabs[0],null);
    savedDrafts.tabs[0]={model:'',provider:'kie',search:'пкщл',values:{},sourceFiles:[]};
    await win.loadFile(path.join(appRoot,'src/index.html'));
    await win.webContents.executeJavaScript(`new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{if(draftsReady){clearInterval(t);resolve();}else if(++n>100){clearInterval(t);reject(new Error($('status').textContent));}},30);})`);
    const afterEmpty=await win.webContents.executeJavaScript(`(async()=>{switchWorkTab(4);return {input:await collectInput(),error:$('status').textContent.includes('Модель сохранённого черновика отсутствует')};})()`);
    assert.equal(afterEmpty.input.prompt,'Fifth preserved scene');assert.equal(afterEmpty.error,false);
    console.log('PASS: Empty-model drafts do not block remaining workspaces; new empty search saves as an unused slot.');
    await win.webContents.executeJavaScript('window.scrollTo(0,0)');
    if(process.argv.includes('--screenshot')){const fs=require('node:fs/promises');await fs.mkdir(path.resolve(__dirname,'../artifacts'),{recursive:true});await fs.writeFile(path.resolve(__dirname,'../artifacts/preview-layout.png'),(await win.webContents.capturePage()).toPNG());}
    console.log('PASS: History repeat keeps the saved source and enqueues without reselecting or uploading it.');
    console.log('PASS: Electron rendered '+count+' model forms; nested restore, omitted values, false boolean, branch selection and list reordering verified; no API requests.');
    win.destroy();app.exit(0);
  }catch(error){console.error(error);if(win)win.destroy();app.exit(1);}
});
