export type MusicEditing = { volume: number; start: number; trimStart: number; fadeIn: number; fadeOut: number; sourceDuration?: number };
export type SceneEditing = { trimStart?: number; sourceDuration?: number; fit?: 'contain' | 'cover'; scale?: number; offsetX?: number; offsetY?: number;
  motion?: 'none' | 'zoom-in' | 'zoom-out'; transition?: 'cut' | 'fade' | 'slide'; transitionSeconds?: number; volume?: number;
  audioFadeIn?: number; audioFadeOut?: number; captionStart?: number; captionEnd?: number; captionSize?: number;
  captionColor?: string; captionBackground?: string; captionPosition?: 'top' | 'center' | 'bottom' };
export type Scene = SceneEditing & { id: string; kind: 'title' | 'image' | 'video'; src?: string; title: string; seconds: number; name?: string };
export function sceneEditing(scene: Scene): Required<Omit<SceneEditing, 'sourceDuration'>> & { sourceDuration?: number };
export function musicEditing(value?: Partial<MusicEditing>): MusicEditing;
export function trimScene(scene: Scene, start: number, end: number): Scene;
export function splitScene(scene: Scene, seconds: number, id: string): [Scene, Scene];
export const FPS: number;
export const MAX_SCENES: number;
export const MAX_SECONDS: number;
export const MAX_STILL_SECONDS: number;
export const FORMATS: Record<'landscape' | 'portrait' | 'square', [number, number]>;
export type TimelineScene = Scene & ReturnType<typeof sceneEditing> & { from: number; durationInFrames: number; fadeIn: number; fadeOut: number; incomingTransition: string };
export function timeline(scenes: Scene[]): { scenes: TimelineScene[]; durationInFrames: number };
