const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  openKieSession: () => ipcRenderer.invoke('kie-session:open'),
  clearKieSession: () => ipcRenderer.invoke('kie-session:clear'),
  kieSessionDiagnostics: () => ipcRenderer.invoke('kie-session:diagnostics'),
  kieSessionStatus: () => ipcRenderer.invoke('kie-session:status'),
  getKieSessionQuote: (value) => ipcRenderer.invoke('kie-session:quote',value),
  costSettings: () => ipcRenderer.invoke('costs:get'),
  setCreditRate: (value) => ipcRenderer.invoke('costs:set',value),
  getTariffs: (force=false) => ipcRenderer.invoke('tariffs:get',force),
  getTariffDescriptions: () => ipcRenderer.invoke('tariffs:descriptions'),
  getPriceAudit: () => ipcRenderer.invoke('price-audit:get'),
  savePriceAudit: (value) => ipcRenderer.invoke('price-audit:save',value),
  autoPriceAudit: () => ipcRenderer.invoke('price-audit:auto'),
  getFavoriteModels: () => ipcRenderer.invoke('favorites:get'),
  setFavoriteModels: (ids) => ipcRenderer.invoke('favorites:set',ids),
  listTemplates: () => ipcRenderer.invoke('templates:list'),
  saveTemplate: (value) => ipcRenderer.invoke('templates:save',value),
  removeTemplate: (id) => ipcRenderer.invoke('templates:remove',id),
  loadDrafts: () => ipcRenderer.invoke('drafts:load'),
  saveDrafts: (drafts) => ipcRenderer.invoke('drafts:save',drafts),
  finishClose: () => ipcRenderer.send('drafts:close'),
  saveSource: (file) => ipcRenderer.invoke('source:save',file),
  sourcePreview: (ref) => ipcRenderer.invoke('source:preview',ref),
  queueStatus: () => ipcRenderer.invoke('queue:status'),
  setConcurrency: (value) => ipcRenderer.invoke('queue:concurrency',value),
  startQueue: () => ipcRenderer.invoke('queue:start'),
  pauseQueue: () => ipcRenderer.invoke('queue:pause'),
  cancelQueued: (id) => ipcRenderer.invoke('queue:cancel',id),
  removeQueued: (id) => ipcRenderer.invoke('queue:remove',id),
  clearQueue: () => ipcRenderer.invoke('queue:clear'),
  acknowledgeTask: (id) => ipcRenderer.invoke('queue:acknowledge',id),
  onQueueChanged: (callback) => { const handler=()=>callback();ipcRenderer.on('queue:changed',handler);return ()=>ipcRenderer.removeListener('queue:changed',handler); },
  testNotification: () => ipcRenderer.invoke('notification:test'),
  storageSettings: () => ipcRenderer.invoke('storage:get'),
  chooseFolder: () => ipcRenderer.invoke('storage:folder'),
  setAutoSave: (enabled) => ipcRenderer.invoke('storage:auto',enabled),
  saveResults: (id) => ipcRenderer.invoke('results:save',id),
  revealResult: (id,index) => ipcRenderer.invoke('results:reveal',id,index),
  getHistory: () => ipcRenderer.invoke('history:list'),
  getCatalog: () => ipcRenderer.invoke("catalog:get"),
  keyStatus: (providerId) => ipcRenderer.invoke("key:status", providerId),
  saveKey: (providerId, key) => ipcRenderer.invoke("key:save", providerId, key),
  getBalance: (providerId, reset=false) => ipcRenderer.invoke("balance:get", providerId, reset),
  uploadFile: (providerId, file) => ipcRenderer.invoke("file:upload", providerId, file),
  createTask: (request) => ipcRenderer.invoke("task:create", request),
  getTask: (providerId, taskId) => ipcRenderer.invoke("task:get", providerId, taskId)
});
